### ISSUE TITLE
Same product issue

### ISSUE THREAD

**Issue by smahmuddz** [FourLineCode/cse489-project#1]
We have to update the current existing same product while adding the same product again, not separately.

![Screenshot_2022-05-05-23-06-04-640_cse489.ewubd.mini_project.jpg](https://user-images.githubusercontent.com/85384973/166976487-3ad91730-f2a7-43ee-9d92-6e4e19b43d58.jpg)

**Comment by FourLineCode** [comment]
hopefully fixed
